//! Registry enums backing the Brain framework.
//!
//! Vanilla keys brain state on three registries: `memory_module_type` (what a mob can
//! remember), `sensor_type` (what refreshes those memories) and `activity` (which
//! behaviour set is currently eligible). These are generated from the jar so the sets
//! cannot silently drift from the reference.



/// A slot of brain state a mob can remember.
///
/// Generated from the `minecraft:memory_module_type` registry of the pinned 26.2 server jar
/// (`comparison/inventory/26.2/registries.json`); regenerate rather than editing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum MemoryModuleType {
    AdmiringDisabled,
    AdmiringItem,
    AngryAt,
    AteRecently,
    AttackCoolingDown,
    AttackTarget,
    AttackTargetCooldown,
    AvoidTarget,
    BreedTarget,
    BreezeJumpCooldown,
    BreezeJumpInhaling,
    BreezeJumpTarget,
    BreezeLeavingWater,
    BreezeShoot,
    BreezeShootCharging,
    BreezeShootCooldown,
    BreezeShootRecover,
    CantReachWalkTargetSince,
    CelebrateLocation,
    ChargeCooldownTicks,
    Dancing,
    DangerDetectedRecently,
    DigCooldown,
    DisableWalkToAdmireItem,
    DisturbanceLocation,
    DoorsToClose,
    Dummy,
    GazeCooldownTicks,
    GolemDetectedRecently,
    HasHuntingCooldown,
    HeardBellTime,
    HidingPlace,
    Home,
    HuntedRecently,
    HurtBy,
    HurtByEntity,
    InteractionTarget,
    IsEmerging,
    IsInWater,
    IsPanicking,
    IsPregnant,
    IsSniffing,
    IsTempted,
    ItemPickupCooldownTicks,
    JobSite,
    LastSlept,
    LastWoken,
    LastWorkedAtPoi,
    LikedNoteblock,
    LikedNoteblockCooldownTicks,
    LikedPlayer,
    LongJumpCoolingDown,
    LongJumpMidJump,
    LookTarget,
    MeetingPoint,
    Mobs,
    NearbyAdultPiglins,
    NearestAttackable,
    NearestBed,
    NearestHostile,
    NearestPlayerHoldingWantedItem,
    NearestPlayers,
    NearestRepellent,
    NearestTargetablePlayerNotWearingGold,
    NearestVisibleAdult,
    NearestVisibleAdultHoglins,
    NearestVisibleAdultPiglin,
    NearestVisibleAdultPiglins,
    NearestVisibleBabyHoglin,
    NearestVisibleHuntableHoglin,
    NearestVisibleNemesis,
    NearestVisiblePlayer,
    NearestVisibleTargetablePlayer,
    NearestVisibleTargetablePlayers,
    NearestVisibleWantedItem,
    NearestVisibleZombified,
    Pacified,
    Path,
    PlayDeadTicks,
    PotentialJobSite,
    RamCooldownTicks,
    RamTarget,
    RecentProjectile,
    RideTarget,
    RoarSoundCooldown,
    RoarSoundDelay,
    RoarTarget,
    SecondaryJobSite,
    SniffCooldown,
    SnifferDigging,
    SnifferExploredPositions,
    SnifferHappy,
    SnifferSniffingTarget,
    SonicBoomCooldown,
    SonicBoomSoundCooldown,
    SonicBoomSoundDelay,
    SpearChargePosition,
    SpearEngageTime,
    SpearFleeingPosition,
    SpearFleeingTime,
    SpearStatus,
    TemptationCooldownTicks,
    TemptingPlayer,
    TimeTryingToReachAdmireItem,
    TouchCooldown,
    TransportItemsCooldownTicks,
    UniversalAnger,
    UnreachableTongueTargets,
    UnreachableTransportBlockPositions,
    VibrationCooldown,
    VisibleAdultHoglinCount,
    VisibleAdultPiglinCount,
    VisibleMobs,
    VisibleVillagerBabies,
    VisitedBlockPositions,
    WalkTarget,
}

impl MemoryModuleType {
    /// Every MemoryModuleType in registry order.
    pub const ALL: [Self; 116] = [
        Self::AdmiringDisabled,
        Self::AdmiringItem,
        Self::AngryAt,
        Self::AteRecently,
        Self::AttackCoolingDown,
        Self::AttackTarget,
        Self::AttackTargetCooldown,
        Self::AvoidTarget,
        Self::BreedTarget,
        Self::BreezeJumpCooldown,
        Self::BreezeJumpInhaling,
        Self::BreezeJumpTarget,
        Self::BreezeLeavingWater,
        Self::BreezeShoot,
        Self::BreezeShootCharging,
        Self::BreezeShootCooldown,
        Self::BreezeShootRecover,
        Self::CantReachWalkTargetSince,
        Self::CelebrateLocation,
        Self::ChargeCooldownTicks,
        Self::Dancing,
        Self::DangerDetectedRecently,
        Self::DigCooldown,
        Self::DisableWalkToAdmireItem,
        Self::DisturbanceLocation,
        Self::DoorsToClose,
        Self::Dummy,
        Self::GazeCooldownTicks,
        Self::GolemDetectedRecently,
        Self::HasHuntingCooldown,
        Self::HeardBellTime,
        Self::HidingPlace,
        Self::Home,
        Self::HuntedRecently,
        Self::HurtBy,
        Self::HurtByEntity,
        Self::InteractionTarget,
        Self::IsEmerging,
        Self::IsInWater,
        Self::IsPanicking,
        Self::IsPregnant,
        Self::IsSniffing,
        Self::IsTempted,
        Self::ItemPickupCooldownTicks,
        Self::JobSite,
        Self::LastSlept,
        Self::LastWoken,
        Self::LastWorkedAtPoi,
        Self::LikedNoteblock,
        Self::LikedNoteblockCooldownTicks,
        Self::LikedPlayer,
        Self::LongJumpCoolingDown,
        Self::LongJumpMidJump,
        Self::LookTarget,
        Self::MeetingPoint,
        Self::Mobs,
        Self::NearbyAdultPiglins,
        Self::NearestAttackable,
        Self::NearestBed,
        Self::NearestHostile,
        Self::NearestPlayerHoldingWantedItem,
        Self::NearestPlayers,
        Self::NearestRepellent,
        Self::NearestTargetablePlayerNotWearingGold,
        Self::NearestVisibleAdult,
        Self::NearestVisibleAdultHoglins,
        Self::NearestVisibleAdultPiglin,
        Self::NearestVisibleAdultPiglins,
        Self::NearestVisibleBabyHoglin,
        Self::NearestVisibleHuntableHoglin,
        Self::NearestVisibleNemesis,
        Self::NearestVisiblePlayer,
        Self::NearestVisibleTargetablePlayer,
        Self::NearestVisibleTargetablePlayers,
        Self::NearestVisibleWantedItem,
        Self::NearestVisibleZombified,
        Self::Pacified,
        Self::Path,
        Self::PlayDeadTicks,
        Self::PotentialJobSite,
        Self::RamCooldownTicks,
        Self::RamTarget,
        Self::RecentProjectile,
        Self::RideTarget,
        Self::RoarSoundCooldown,
        Self::RoarSoundDelay,
        Self::RoarTarget,
        Self::SecondaryJobSite,
        Self::SniffCooldown,
        Self::SnifferDigging,
        Self::SnifferExploredPositions,
        Self::SnifferHappy,
        Self::SnifferSniffingTarget,
        Self::SonicBoomCooldown,
        Self::SonicBoomSoundCooldown,
        Self::SonicBoomSoundDelay,
        Self::SpearChargePosition,
        Self::SpearEngageTime,
        Self::SpearFleeingPosition,
        Self::SpearFleeingTime,
        Self::SpearStatus,
        Self::TemptationCooldownTicks,
        Self::TemptingPlayer,
        Self::TimeTryingToReachAdmireItem,
        Self::TouchCooldown,
        Self::TransportItemsCooldownTicks,
        Self::UniversalAnger,
        Self::UnreachableTongueTargets,
        Self::UnreachableTransportBlockPositions,
        Self::VibrationCooldown,
        Self::VisibleAdultHoglinCount,
        Self::VisibleAdultPiglinCount,
        Self::VisibleMobs,
        Self::VisibleVillagerBabies,
        Self::VisitedBlockPositions,
        Self::WalkTarget,
    ];

    /// The registry name, without the `minecraft:` namespace.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::AdmiringDisabled => "admiring_disabled",
            Self::AdmiringItem => "admiring_item",
            Self::AngryAt => "angry_at",
            Self::AteRecently => "ate_recently",
            Self::AttackCoolingDown => "attack_cooling_down",
            Self::AttackTarget => "attack_target",
            Self::AttackTargetCooldown => "attack_target_cooldown",
            Self::AvoidTarget => "avoid_target",
            Self::BreedTarget => "breed_target",
            Self::BreezeJumpCooldown => "breeze_jump_cooldown",
            Self::BreezeJumpInhaling => "breeze_jump_inhaling",
            Self::BreezeJumpTarget => "breeze_jump_target",
            Self::BreezeLeavingWater => "breeze_leaving_water",
            Self::BreezeShoot => "breeze_shoot",
            Self::BreezeShootCharging => "breeze_shoot_charging",
            Self::BreezeShootCooldown => "breeze_shoot_cooldown",
            Self::BreezeShootRecover => "breeze_shoot_recover",
            Self::CantReachWalkTargetSince => "cant_reach_walk_target_since",
            Self::CelebrateLocation => "celebrate_location",
            Self::ChargeCooldownTicks => "charge_cooldown_ticks",
            Self::Dancing => "dancing",
            Self::DangerDetectedRecently => "danger_detected_recently",
            Self::DigCooldown => "dig_cooldown",
            Self::DisableWalkToAdmireItem => "disable_walk_to_admire_item",
            Self::DisturbanceLocation => "disturbance_location",
            Self::DoorsToClose => "doors_to_close",
            Self::Dummy => "dummy",
            Self::GazeCooldownTicks => "gaze_cooldown_ticks",
            Self::GolemDetectedRecently => "golem_detected_recently",
            Self::HasHuntingCooldown => "has_hunting_cooldown",
            Self::HeardBellTime => "heard_bell_time",
            Self::HidingPlace => "hiding_place",
            Self::Home => "home",
            Self::HuntedRecently => "hunted_recently",
            Self::HurtBy => "hurt_by",
            Self::HurtByEntity => "hurt_by_entity",
            Self::InteractionTarget => "interaction_target",
            Self::IsEmerging => "is_emerging",
            Self::IsInWater => "is_in_water",
            Self::IsPanicking => "is_panicking",
            Self::IsPregnant => "is_pregnant",
            Self::IsSniffing => "is_sniffing",
            Self::IsTempted => "is_tempted",
            Self::ItemPickupCooldownTicks => "item_pickup_cooldown_ticks",
            Self::JobSite => "job_site",
            Self::LastSlept => "last_slept",
            Self::LastWoken => "last_woken",
            Self::LastWorkedAtPoi => "last_worked_at_poi",
            Self::LikedNoteblock => "liked_noteblock",
            Self::LikedNoteblockCooldownTicks => "liked_noteblock_cooldown_ticks",
            Self::LikedPlayer => "liked_player",
            Self::LongJumpCoolingDown => "long_jump_cooling_down",
            Self::LongJumpMidJump => "long_jump_mid_jump",
            Self::LookTarget => "look_target",
            Self::MeetingPoint => "meeting_point",
            Self::Mobs => "mobs",
            Self::NearbyAdultPiglins => "nearby_adult_piglins",
            Self::NearestAttackable => "nearest_attackable",
            Self::NearestBed => "nearest_bed",
            Self::NearestHostile => "nearest_hostile",
            Self::NearestPlayerHoldingWantedItem => "nearest_player_holding_wanted_item",
            Self::NearestPlayers => "nearest_players",
            Self::NearestRepellent => "nearest_repellent",
            Self::NearestTargetablePlayerNotWearingGold => "nearest_targetable_player_not_wearing_gold",
            Self::NearestVisibleAdult => "nearest_visible_adult",
            Self::NearestVisibleAdultHoglins => "nearest_visible_adult_hoglins",
            Self::NearestVisibleAdultPiglin => "nearest_visible_adult_piglin",
            Self::NearestVisibleAdultPiglins => "nearest_visible_adult_piglins",
            Self::NearestVisibleBabyHoglin => "nearest_visible_baby_hoglin",
            Self::NearestVisibleHuntableHoglin => "nearest_visible_huntable_hoglin",
            Self::NearestVisibleNemesis => "nearest_visible_nemesis",
            Self::NearestVisiblePlayer => "nearest_visible_player",
            Self::NearestVisibleTargetablePlayer => "nearest_visible_targetable_player",
            Self::NearestVisibleTargetablePlayers => "nearest_visible_targetable_players",
            Self::NearestVisibleWantedItem => "nearest_visible_wanted_item",
            Self::NearestVisibleZombified => "nearest_visible_zombified",
            Self::Pacified => "pacified",
            Self::Path => "path",
            Self::PlayDeadTicks => "play_dead_ticks",
            Self::PotentialJobSite => "potential_job_site",
            Self::RamCooldownTicks => "ram_cooldown_ticks",
            Self::RamTarget => "ram_target",
            Self::RecentProjectile => "recent_projectile",
            Self::RideTarget => "ride_target",
            Self::RoarSoundCooldown => "roar_sound_cooldown",
            Self::RoarSoundDelay => "roar_sound_delay",
            Self::RoarTarget => "roar_target",
            Self::SecondaryJobSite => "secondary_job_site",
            Self::SniffCooldown => "sniff_cooldown",
            Self::SnifferDigging => "sniffer_digging",
            Self::SnifferExploredPositions => "sniffer_explored_positions",
            Self::SnifferHappy => "sniffer_happy",
            Self::SnifferSniffingTarget => "sniffer_sniffing_target",
            Self::SonicBoomCooldown => "sonic_boom_cooldown",
            Self::SonicBoomSoundCooldown => "sonic_boom_sound_cooldown",
            Self::SonicBoomSoundDelay => "sonic_boom_sound_delay",
            Self::SpearChargePosition => "spear_charge_position",
            Self::SpearEngageTime => "spear_engage_time",
            Self::SpearFleeingPosition => "spear_fleeing_position",
            Self::SpearFleeingTime => "spear_fleeing_time",
            Self::SpearStatus => "spear_status",
            Self::TemptationCooldownTicks => "temptation_cooldown_ticks",
            Self::TemptingPlayer => "tempting_player",
            Self::TimeTryingToReachAdmireItem => "time_trying_to_reach_admire_item",
            Self::TouchCooldown => "touch_cooldown",
            Self::TransportItemsCooldownTicks => "transport_items_cooldown_ticks",
            Self::UniversalAnger => "universal_anger",
            Self::UnreachableTongueTargets => "unreachable_tongue_targets",
            Self::UnreachableTransportBlockPositions => "unreachable_transport_block_positions",
            Self::VibrationCooldown => "vibration_cooldown",
            Self::VisibleAdultHoglinCount => "visible_adult_hoglin_count",
            Self::VisibleAdultPiglinCount => "visible_adult_piglin_count",
            Self::VisibleMobs => "visible_mobs",
            Self::VisibleVillagerBabies => "visible_villager_babies",
            Self::VisitedBlockPositions => "visited_block_positions",
            Self::WalkTarget => "walk_target",
        }
    }
}

/// A periodic scan that refreshes memories.
///
/// Generated from the `minecraft:sensor_type` registry of the pinned 26.2 server jar
/// (`comparison/inventory/26.2/registries.json`); regenerate rather than editing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SensorType {
    ArmadilloScareDetected,
    AxolotlAttackables,
    BreezeAttackEntitySensor,
    Dummy,
    FoodTemptations,
    FrogAttackables,
    FrogTemptations,
    GolemDetected,
    HoglinSpecificSensor,
    HurtBy,
    IsInWater,
    NautilusTemptations,
    NearestAdult,
    NearestAdultAnyType,
    NearestBed,
    NearestItems,
    NearestLivingEntities,
    NearestPlayers,
    PiglinBruteSpecificSensor,
    PiglinSpecificSensor,
    SecondaryPois,
    VillagerBabies,
    VillagerHostiles,
    WardenEntitySensor,
}

impl SensorType {
    /// Every SensorType in registry order.
    pub const ALL: [Self; 24] = [
        Self::ArmadilloScareDetected,
        Self::AxolotlAttackables,
        Self::BreezeAttackEntitySensor,
        Self::Dummy,
        Self::FoodTemptations,
        Self::FrogAttackables,
        Self::FrogTemptations,
        Self::GolemDetected,
        Self::HoglinSpecificSensor,
        Self::HurtBy,
        Self::IsInWater,
        Self::NautilusTemptations,
        Self::NearestAdult,
        Self::NearestAdultAnyType,
        Self::NearestBed,
        Self::NearestItems,
        Self::NearestLivingEntities,
        Self::NearestPlayers,
        Self::PiglinBruteSpecificSensor,
        Self::PiglinSpecificSensor,
        Self::SecondaryPois,
        Self::VillagerBabies,
        Self::VillagerHostiles,
        Self::WardenEntitySensor,
    ];

    /// The registry name, without the `minecraft:` namespace.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::ArmadilloScareDetected => "armadillo_scare_detected",
            Self::AxolotlAttackables => "axolotl_attackables",
            Self::BreezeAttackEntitySensor => "breeze_attack_entity_sensor",
            Self::Dummy => "dummy",
            Self::FoodTemptations => "food_temptations",
            Self::FrogAttackables => "frog_attackables",
            Self::FrogTemptations => "frog_temptations",
            Self::GolemDetected => "golem_detected",
            Self::HoglinSpecificSensor => "hoglin_specific_sensor",
            Self::HurtBy => "hurt_by",
            Self::IsInWater => "is_in_water",
            Self::NautilusTemptations => "nautilus_temptations",
            Self::NearestAdult => "nearest_adult",
            Self::NearestAdultAnyType => "nearest_adult_any_type",
            Self::NearestBed => "nearest_bed",
            Self::NearestItems => "nearest_items",
            Self::NearestLivingEntities => "nearest_living_entities",
            Self::NearestPlayers => "nearest_players",
            Self::PiglinBruteSpecificSensor => "piglin_brute_specific_sensor",
            Self::PiglinSpecificSensor => "piglin_specific_sensor",
            Self::SecondaryPois => "secondary_pois",
            Self::VillagerBabies => "villager_babies",
            Self::VillagerHostiles => "villager_hostiles",
            Self::WardenEntitySensor => "warden_entity_sensor",
        }
    }
}

/// A named set of behaviours that can be active together.
///
/// Generated from the `minecraft:activity` registry of the pinned 26.2 server jar
/// (`comparison/inventory/26.2/registries.json`); regenerate rather than editing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Activity {
    AdmireItem,
    Avoid,
    Celebrate,
    Core,
    Dig,
    Emerge,
    Fight,
    Hide,
    Idle,
    Investigate,
    LaySpawn,
    LongJump,
    Meet,
    Panic,
    Play,
    PlayDead,
    PreRaid,
    Raid,
    Ram,
    Rest,
    Ride,
    Roar,
    Sniff,
    Swim,
    Tongue,
    Work,
}

impl Activity {
    /// Every Activity in registry order.
    pub const ALL: [Self; 26] = [
        Self::AdmireItem,
        Self::Avoid,
        Self::Celebrate,
        Self::Core,
        Self::Dig,
        Self::Emerge,
        Self::Fight,
        Self::Hide,
        Self::Idle,
        Self::Investigate,
        Self::LaySpawn,
        Self::LongJump,
        Self::Meet,
        Self::Panic,
        Self::Play,
        Self::PlayDead,
        Self::PreRaid,
        Self::Raid,
        Self::Ram,
        Self::Rest,
        Self::Ride,
        Self::Roar,
        Self::Sniff,
        Self::Swim,
        Self::Tongue,
        Self::Work,
    ];

    /// The registry name, without the `minecraft:` namespace.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::AdmireItem => "admire_item",
            Self::Avoid => "avoid",
            Self::Celebrate => "celebrate",
            Self::Core => "core",
            Self::Dig => "dig",
            Self::Emerge => "emerge",
            Self::Fight => "fight",
            Self::Hide => "hide",
            Self::Idle => "idle",
            Self::Investigate => "investigate",
            Self::LaySpawn => "lay_spawn",
            Self::LongJump => "long_jump",
            Self::Meet => "meet",
            Self::Panic => "panic",
            Self::Play => "play",
            Self::PlayDead => "play_dead",
            Self::PreRaid => "pre_raid",
            Self::Raid => "raid",
            Self::Ram => "ram",
            Self::Rest => "rest",
            Self::Ride => "ride",
            Self::Roar => "roar",
            Self::Sniff => "sniff",
            Self::Swim => "swim",
            Self::Tongue => "tongue",
            Self::Work => "work",
        }
    }
}
