"""Convert CollisionStepCoordinates.java JSON output into the checked-in Rust table."""
import json, sys
from pathlib import Path
states = json.loads(Path(sys.argv[1]).read_text())
assert [state for state, _ in states] == list(range(32366))
groups, indices = [], []
for _, coordinates in states:
    if coordinates not in groups:
        groups.append(coordinates)
    indices.append(groups.index(coordinates))
lines = ['// Generated by tools/vanilla/CollisionStepCoordinates.java and generate_step_coordinates.py.',
         '// Java 26.2, complete collision coordinate grids (not flattened box endpoints).',
         'pub const GRIDS: &[[&[f64]; 3]] = &[']
lines += ['    [' + ','.join('&['+','.join(map(repr,axis))+']' for axis in coordinates) + '],' for coordinates in groups]
lines += ['];', 'pub const STATE_GRID: &[u16] = &[']
lines += ['    ' + ','.join(map(str,indices[i:i+64])) + ',' for i in range(0,len(indices),64)]
lines += ['];']
Path('crates/pumpkin-data/src/generated/collision_step_coords.rs').write_text('\n'.join(lines)+'\n')
print(len(indices), 'states;', len(groups), 'coordinate grids')
